

module Info
  STATUS = {
    #all data needs to be in float that is xxx.x flormat
    #Information
    "100.0" => "Info- Continue", "101.0" => "Info - Switching protocol",
    #Success
    "200.0" => "OK - request", "201.0" => "OK - Created", "202.0" => "OK- Accepted", "203.0" => "OK - Nonauthoritative info",
    "204.0" => "OK - No content", "205.0" =>"OK - Reset content", "206.0" => "OK - Partial content",
    #Client error
    "400.1" => "ERROR - Invalid Destination Header", "400.2" => "ERROR - Invalid Depth Header", "400.3" => "ERROR -  Invalid If Header",
    "400.4" => "ERROR - Invalid Overwrite Header", "400.5" => "ERROR - Invalid Translate Header",
    "400.6" => "ERROR - Invalid Request Body", "400.7" => "ERROR - Invalid Content Length", "400.8" => "ERROR - Invalid Timeout",
    "400.9" => "ERROR - Invalid Lock Token", "401.0" => "ERROR - Access denied",
    "401.1" => "ERROR - Logon failed.",
    "401.2" => "ERROR - Logon failed due to server configuration.",
    "401.3" => "ERROR - Unauthorized due to ACL on resource",
    "401.4" => "ERROR - Authorization failed by filter.",
    "401.5" => "ERROR - Authorization failed by ISAPI/CGI application.",
    "403.0" => "ERROR - Forbidden",
    "403.1" => "Error -  Execute access forbidden.",
    "403.2" => "Error - Read access forbidden.",
    "403.3" => "Error - Write access forbidden.",
    "403.4" => "Error - SSL required.",
    "403.5" => "Error - SSL 128 required.",
    "403.6" => "Error - IP address rejected.",
    "403.7" => "Error - Client certificate required.",
    "403.8" => "Error - Site access denied.",
    "403.9" => "Error - Forbidden: Too many clients are trying to connect to the web server.",
    "403.10" => "Error - Forbidden: web server is configured to deny Execute access.",
    "403.11" => "Error - Forbidden: Password has been changed.",
    "403.12" => "Error - Mapper denied access.",
    "403.13" => "Error - Client certificate revoked.",
    "403.14" => "Error - Directory listing denied.",
    "403.15" => "Error - Forbidden: Client access licenses have exceeded limits on the web server.",
    "403.16" => "Error - Client certificate is untrusted or invalid.",
    "403.17" => "Error - Client certificate has expired or is not yet valid.",
    "403.18" => "Error - Cannot execute requested URL in the current application pool.",
    "403.19" => "Error - Cannot execute CGI applications for the client in this application pool.",
    "403.20" => "Error - Forbidden: Passport logon failed.",
    "403.21" => "Error - Forbidden: Source access denied.",
    "403.22" => "Error - Forbidden: Infinite depth is denied.",
    "403.502" => "Error - Forbidden: Too many requests from the same client IP; Dynamic IP Restriction limit reached.",
    "404.0" => "Error - Not found.",
    "404.1" => "Error - Site Not Found.",
    "404.2" => "Error - ISAPI or CGI restriction.",
    "404.3" => "Error - MIME type restriction.",
    "404.4" => "Error - No handler configured.",
    "404.6" => "Error - Verb denied.",
    "404.7" => "Error - File extension denied.",
    "404.8" => "Error - Hidden namespace.",
    "404.9" => "Error - File attribute hidden.",
    "404.10" => "Error - Request header too long.",
    "404.11" => "Error - Request contains double escape sequence.",
    "404.12" => "Error - Request contains high-bit characters.",
    "404.13" => "Error - Content length too large.",
    "404.14" => "Error - Request URL too long.",
    "404.15" => "Error - Query string too long.",
    "404.16" => "Error - DAV request sent to the static file handler.",
    "404.17" => "Error - Dynamic content mapped to the static file handler via a wildcard MIME mapping.",
    "404.18" => "Error - Querystring sequence denied.",
    "404.19" => "Error - Denied by filtering rule.",
    "404.20" => "Error - Too Many URL Segments",
    "405.0" => "Error - Method Not Allowed.",
    "406.0" => "Error - Client browser does not accept the MIME type of the requested page.",
    "408.0" => "Error - Request timed out.",
    "412.0" => "Error - Precondition failed.",
    "500.0" => "Error - Module or ISAPI error occurred.",
    "500.11" => "Error - Application is shutting down on the web server.",
    "500.12" => "Error - Application is busy restarting on the web server.",
    "500.13" => "Error - Web server is too busy.",
    "500.15" => "Error - Direct requests for Global.asax are not allowed.",
    "500.19" => "Error - Configuration data is invalid.",
    "500.21" => "Error - Module not recognized.",
    "500.22" => "Error - An ASP.NET httpModules configuration does not apply in Managed Pipeline mode.",
    "500.23" => "Error - An ASP.NET httpHandlers configuration does not apply in Managed Pipeline mode.",
    "500.24" => "Error - An ASP.NET impersonation configuration does not apply in Managed Pipeline mode.",
    "500.50" => "Error - A rewrite error occurred during RQ_BEGIN_REQUEST notification handling. A configuration or inbound rule execution error occurred.",
    "500.51" => "Error - A rewrite error occurred during GL_PRE_BEGIN_REQUEST notification handling. A global configuration or global rule execution error occurred.",
    "500.52" => "Error - A rewrite error occurred during RQ_SEND_RESPONSE notification handling. An outbound rule execution occurred.",
    "500.53" => "Error - A rewrite error occurred during RQ_RELEASE_REQUEST_STATE notification handling. An outbound rule execution error occurred. The rule is configured to be executed before the output user cache gets updated.",
    "500.100" => "Error - Internal ASP error.",
    "501" => "Error - Header values specify a configuration that is not implemented.",
    "502.0" => "Error - Web server received an invalid response while acting as a gateway or proxy.",
    "502.1" => "Error - CGI application timeout.",
    "502.2" => "Error - Bad gateway: Premature Exit.",
    "502.3" => "Error - Bad Gateway: Forwarder Connection Error (ARR).",
    "502.4" => "Error - Bad Gateway: No Server (ARR).",
    "503" => "Error - Service unavailable.",
    "503.0" => "Error - Application pool unavailable.",
    "503.2" => "Error - Concurrent request limit exceeded.",
    "503.3" => "Error - ASP.NET queue full"
      }
  def self.explain_status(string)
    STATUS[string]
  end
end
